# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  testwsl:
    name: "test wsl"
    runs-on: windows-latest
    defaults:
      run:
        shell: wsl-bash {0}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v3
      - name: Setup Node v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: Vampire/setup-wsl@v2
        with:
          distribution: Ubuntu-20.04
          additional-packages:
            dos2unix
            xclip
      - run: which wslpath
      - run: which touch
      - run: ls
      - run: pwd
      - run: |
          npm ci
          node index.cjs

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
