# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  testwsl:
    name: "test wsl"
    runs-on: windows-latest
    outputs:
      powershell_path: ${{ steps.powershell_path.outputs.value }}
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - id: powershell_path
        run: echo "value="('where powershell') >> "$GITHUB_OUTPUT"

      - name: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v3
      - name: Setup Node v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: Vampire/setup-wsl@v2
        with:
          distribution: Ubuntu-20.04
          additional-packages:
            dos2unix
            xclip
      - shell: wsl-bash {0}
        run: echo ${{ steps.powershell_path.outputs.value }}
      - shell: wsl-bash {0}
        run: dos2unix *.sh
      - shell: wsl-bash {0}
        run: . linux-set-clipboard-png ./telesoho_logo_80x80.png
      - run: 
          npm i
          node index.cjs

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
