# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: "(${{ matrix.os }})"
    if: matrix.os == 'wsl'
    runs-on: ${{ windows-latest }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3      
      - uses: Vampire/setup-wsl@v2
        with:
          distribution: Ubuntu-20.04
      - shell: wsl-bash {0}
        run: id
      - run: touch ./test.txt
      - run: pwd
      - run: ls
      - run: powershell /?
      - run: pwsh /?
      - run: wslpath ./test.txt
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest, wsl]
        node-version: [16.x]  # This workflow contains a single job called "build"


        
