# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  testwsl:
    name: "test wsl"
    runs-on: windows-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3   
      - uses: Vampire/setup-wsl@v2
        with:
          distribution: Ubuntu-20.04
      - shell: wsl-bash {0}
        run: id
      - run: .\set-clipboard-png.ps1 .\telesoho_logo_80x80.png
      - run: pwd
      - run: .\save-clipboard-png.ps1 $PWD\test.png
    strategy:
      fail-fast: false

  testos:
    name: "(${{ matrix.os }})"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [16.x]
    
    steps:
      - name: Setup ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y xclip
